import type { NextPage } from 'next';
import Head from 'next/head';
import { HomeView } from '../views';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pisces | The Renting of App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <HomeView />
    </div>
  )
}

export default Home
